### ISSUE TITLE
[Bug] ゲームオーバー後にもう一度始めようとして落ちない　

### ISSUE THREAD

**Issue by scnsh** [scnsh/dq-like-rpg#8]
出てたログ

```
thread 'Compute Task Pool (0)' panicked at 'called `Result::unwrap()` on an `Err` value: MultipleEntities("bevy_ecs::system::query::Query<&rpg::components::CharacterStatus, bevy_ecs::query::filter::With<rpg::components::Player>>")', src/systems/setup_status_ui.rs:12:47thread '
Compute Task Pool (3)' panicked at 'called `Result::unwrap()` on an `Err` value: MultipleEntities("bevy_ecs::system::query::Query<&rpg::components::Inventory, bevy_ecs::query::filter::With<rpg::components::Player>>")', src/systems/setup_map_ui.rs:11:46
stack backtrace:
```

**Comment by scnsh** [comment]
以下を対応済み
- Player component を削除するように修正
- Camera の 位置や状態を初期状態に戻すように修正
